"""Pack a trained model into docs/model.js so the web page can run it.

    python train.py          # makes model.npz
    python export_web.py     # makes docs/model.js

The page only *runs* the network (the forward pass); all the learning happens
here in Python. model.js is a plain script that sets one global, MODEL, so the
page also works when index.html is opened straight from disk.

To keep the file small, W1 (512 x 784 = 401,408 numbers, 98% of the model) is
stored as 8-bit integers instead of 32-bit floats: each row is scaled so its
largest weight becomes 127 and then rounded. That makes the file 4x smaller,
and the script checks that it doesn't change the accuracy.
"""
import argparse
import base64
import json
from pathlib import Path

import numpy as np

import network
from mnist import load_mnist

OUT = Path(__file__).resolve().parent / "docs" / "model.js"
NUM_EXAMPLES = 100  # real test images the page can show with "Show me a real one"


def b64(array):
    """Raw bytes of a NumPy array as a base64 string (little-endian, like every browser)."""
    return base64.b64encode(np.ascontiguousarray(array).tobytes()).decode("ascii")


def main():
    parser = argparse.ArgumentParser(description="Export a trained model for the web page.")
    parser.add_argument("--model", default="model.npz", help="model saved by train.py")
    args = parser.parse_args()

    params = dict(np.load(args.model))
    _, _, (X_test, Y_test) = load_mnist()

    # Quantize W1 to int8, one scale per row (per hidden neuron)
    W1 = params["W1"]
    scale = np.abs(W1).max(axis=1, keepdims=True) / 127
    W1_q = np.round(W1 / scale).astype(np.int8)

    original = network.accuracy(params, X_test, Y_test)
    rounded = network.accuracy({**params, "W1": W1_q * scale}, X_test, Y_test)
    print(f"Test accuracy: {original * 100:.2f}% original, {rounded * 100:.2f}% with 8-bit W1")

    # A fixed random sample of test images, as 0-255 bytes
    picks = np.random.default_rng(0).choice(Y_test.size, NUM_EXAMPLES, replace=False)
    examples = np.round(X_test[:, picks].T * 255).astype(np.uint8)  # (NUM_EXAMPLES, 784)

    model = {
        "hidden_size": int(W1.shape[0]),
        "test_accuracy": round(rounded, 4),
        "W1_q": b64(W1_q),                                   # int8, (hidden, 784) row by row
        "W1_scale": b64(scale.astype(np.float32)),           # float32, (hidden,)
        "b1": b64(params["b1"].astype(np.float32)),          # float32, (hidden,)
        "W2": b64(params["W2"].astype(np.float32)),          # float32, (10, hidden) row by row
        "b2": b64(params["b2"].astype(np.float32)),          # float32, (10,)
        "examples": b64(examples),                           # uint8, (NUM_EXAMPLES, 784)
        "example_labels": Y_test[picks].tolist(),
    }
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("// Generated by export_web.py - do not edit by hand.\n"
                   f"window.MODEL = {json.dumps(model)};\n")
    print(f"Wrote {OUT} ({OUT.stat().st_size / 1e6:.2f} MB)")


if __name__ == "__main__":
    main()
