"""Pack a trained model into docs/model.js so the web page can run it.

    python train.py          # makes model.npz and history.npz
    python export_web.py     # makes docs/model.js

The page only *runs* the network (the forward pass); all the learning happens
here in Python. model.js is a plain script that sets one global, MODEL, so the
page also works when index.html is opened straight from disk.

To keep the file small, W1 (512 x 784 = 401,408 numbers, 98% of the model) is
stored as 8-bit integers instead of 32-bit floats: each row is scaled so its
largest weight becomes 127 and then rounded. That makes the file 4x smaller,
and the script checks that it doesn't change the accuracy.

It also packs what the page's later sections show:
  - the training replay, from the snapshots train.py saved in history.npz,
  - every test digit the final network gets wrong.
"""
import argparse
import base64
import json
from pathlib import Path

import numpy as np

import network
from mnist import load_mnist

OUT = Path(__file__).resolve().parent / "docs" / "model.js"
NUM_EXAMPLES = 100   # real test images for the page's "Real example" button
REPLAY_NEURONS = 8   # neurons whose patterns the training replay shows
REPLAY_DIGITS = 12   # test digits whose guesses the training replay shows


def b64(array):
    """Raw bytes of a NumPy array as a base64 string (little-endian, like every browser)."""
    return base64.b64encode(np.ascontiguousarray(array).tobytes()).decode("ascii")


def main():
    parser = argparse.ArgumentParser(description="Export a trained model for the web page.")
    parser.add_argument("--model", default="model.npz", help="model saved by train.py")
    parser.add_argument("--history", default="history.npz", help="snapshots saved by train.py")
    args = parser.parse_args()

    params = dict(np.load(args.model))
    _, _, (X_test, Y_test) = load_mnist()

    # Quantize W1 to int8, one scale per row (per hidden neuron)
    W1 = params["W1"]
    scale = np.abs(W1).max(axis=1, keepdims=True) / 127
    W1_q = np.round(W1 / scale).astype(np.int8)

    original = network.accuracy(params, X_test, Y_test)
    rounded = network.accuracy({**params, "W1": W1_q * scale}, X_test, Y_test)
    print(f"Test accuracy: {original * 100:.2f}% original, {rounded * 100:.2f}% with 8-bit W1")

    # A fixed random sample of test images, as 0-255 bytes
    picks = np.random.default_rng(0).choice(Y_test.size, NUM_EXAMPLES, replace=False)
    examples = to_bytes(X_test[:, picks])  # (NUM_EXAMPLES, 784)

    replay = training_replay(params, np.load(args.history), X_test, Y_test)
    mistakes = all_mistakes({**params, "W1": W1_q * scale}, X_test, Y_test)

    model = {
        "hidden_size": int(W1.shape[0]),
        "test_accuracy": round(rounded, 4),
        "W1_q": b64(W1_q),                                   # int8, (hidden, 784) row by row
        "W1_scale": b64(scale.astype(np.float32)),           # float32, (hidden,)
        "b1": b64(params["b1"].astype(np.float32)),          # float32, (hidden,)
        "W2": b64(params["W2"].astype(np.float32)),          # float32, (10, hidden) row by row
        "b2": b64(params["b2"].astype(np.float32)),          # float32, (10,)
        "examples": b64(examples),                           # uint8, (NUM_EXAMPLES, 784)
        "example_labels": Y_test[picks].tolist(),
        "replay": replay,
        "mistakes": mistakes,
    }
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("// Generated by export_web.py - do not edit by hand.\n"
                   f"window.MODEL = {json.dumps(model)};\n")
    print(f"Wrote {OUT} ({OUT.stat().st_size / 1e6:.2f} MB)")


def to_bytes(images):
    """(784, n) floats in [0, 1] -> (n, 784) bytes 0-255."""
    return np.round(images.T * 255).astype(np.uint8)


def training_replay(params, history, X_test, Y_test):
    """What the network looked like at each snapshot taken during training."""
    snapshots = [{k: history[k][c].astype(np.float32) for k in ("W1", "b1", "W2", "b2")}
                 for c in range(len(history["images_seen"]))]
    probs = np.stack([network.forward(s, X_test)[0] for s in snapshots])  # (snapshots, 10, n)
    guesses = probs.argmax(axis=1)                                        # (snapshots, n)
    correct = guesses == Y_test

    # The neurons with the most say in the final answers: how active they are on
    # average times how strongly they vote
    hidden = np.maximum(params["W1"] @ X_test + params["b1"], 0)
    influence = hidden.mean(axis=1) * np.linalg.norm(params["W2"], axis=0)
    neurons = np.argsort(influence)[::-1][:REPLAY_NEURONS]
    patterns = history["W1"][:, neurons, :].astype(np.float32)  # (snapshots, neurons, 784)
    patterns /= np.abs(patterns).max(axis=2, keepdims=True)     # each picture scaled to -1..1
    patterns = np.round(patterns * 127).astype(np.int8)

    # Test digits that are learned at different times: right from early on, after
    # a while, only near the end, and never (still wrong at the end)
    count = len(snapshots)
    wrong = ~correct
    last_wrong = np.where(wrong.any(axis=0), count - 1 - np.argmax(wrong[::-1], axis=0), -1)
    learned_at = last_wrong + 1  # the snapshot from which it stays right; count = never
    rng = np.random.default_rng(0)
    groups = [learned_at <= 6, (learned_at > 6) & (learned_at <= 11),
              (learned_at > 11) & (learned_at < count), learned_at == count]
    digits = np.concatenate([rng.choice(np.flatnonzero(g), REPLAY_DIGITS // 4, replace=False)
                             for g in groups])
    digits = digits[np.argsort(Y_test[digits], kind="stable")]
    confidence = np.round(probs.max(axis=1)[:, digits] * 100).astype(np.uint8)

    return {
        "images_seen": history["images_seen"].tolist(),
        "accuracy": [round(float(a), 4) for a in correct.mean(axis=1)],
        "neurons": (neurons + 1).tolist(),                       # numbered from 1 on the page
        "patterns": b64(patterns),                               # int8, (snapshots, neurons, 784)
        "digits": b64(to_bytes(X_test[:, digits])),              # uint8, (digits, 784)
        "digit_labels": Y_test[digits].tolist(),
        "guesses": b64(guesses[:, digits].astype(np.uint8)),     # uint8, (snapshots, digits)
        "confidence": b64(confidence),                           # uint8 percent, (snapshots, digits)
    }


def all_mistakes(params, X_test, Y_test):
    """Every test digit the final network gets wrong, and how many of each digit there are."""
    probs, _ = network.forward(params, X_test)
    guesses = probs.argmax(axis=0)
    wrong = np.flatnonzero(guesses != Y_test)
    return {
        "images": b64(to_bytes(X_test[:, wrong])),               # uint8, (mistakes, 784)
        "labels": Y_test[wrong].tolist(),
        "guesses": guesses[wrong].tolist(),
        "confidence": [round(float(c), 3) for c in probs[:, wrong].max(axis=0)],
        "test_counts": np.bincount(Y_test, minlength=10).tolist(),
    }


if __name__ == "__main__":
    main()
